name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_tag: [ '11-ubuntu', '17-ubuntu', '21-ubuntu', '11-mariner', '17-mariner', '21-mariner', '8-mariner' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker build . \
          --build-arg BASE_IMAGE=mcr.microsoft.com/openjdk/jdk:${{ matrix.base_tag }} \
          --file Dockerfile \
          --tag msopenjdk-freetype:${{ matrix.base_tag }}

    - name: Run Docker container
      run: |
        docker run -ti --rm msopenjdk-freetype:${{ matrix.base_tag }}
