name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jdk_version: [ '11', '17', '21' ]
        base_os: [ 'ubuntu', 'mariner' ]

    steps:
    - uses: actions/checkout@v4

#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        docker build . \
          --build-arg BASE_OS=mcr.microsoft.com/openjdk/jdk:${{ matrix.base_os }} JDK_VERSION=${{ matrix.jdk_version }} \
          --file Dockerfile \
          --tag msopenjdk-freetype:${{ matrix.base_os }}-${{ matrix.jdk_version }}

    - name: Run Docker container
      run: |
        docker run -t -e JDK_VERSION=${{ matrix.jdk_version }} --rm msopenjdk-freetype:${{ matrix.base_os }}-${{ matrix.jdk_version }}
